import {Darumadrop_One, Inter} from 'next/font/google'
import {Analytics} from '@vercel/analytics/next'
import './globals.css'

const displayFont = Darumadrop_One({
  variable: '--font-display',
  subsets: ['latin'],
  weight: ['400']
})

const sansFont = Inter({
  variable: '--font-sans',
  subsets: ['latin'],
  display: 'swap' // or 'optional' to reduce visible swapping
})

// const geistMono = Geist_Mono({
//   variable: '--font-mono',
//   subsets: ['latin']
// })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app'
// }

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={`${sansFont.variable} ${displayFont.variable}`}>
      <body className="font-sans antialiased">
        {children}
        <Analytics />
      </body>
    </html>
  )
}
